### ISSUE TITLE
update the website URL in the repo About section

### ISSUE THREAD

**Issue by mmahmoudian** [UMCUGenetics/hpcguix-web#14]
At the moment in the About section of the repo the website is https://hpcguix.op.umcutrecht.nl/ where at the time of writing this it redirects to: https://hpc.guix.info/browse

I suggest changing the URL in the repo description to match the current URL, and also being placed in the correct field.

This is how it looks at the moment:
![image](https://github.com/UMCUGenetics/hpcguix-web/assets/390889/01173e23-3496-42f0-9be6-61ab0fc7e13a)

Just to save your time (I myself usually forget this too), here is how you can change it (I'm using one of my own repos as example in the next screenshot):

1. Open [the repo](https://github.com/UMCUGenetics/hpcguix-web) while being logged in Github
2. click on the cog in the About section of the repo info
3. delete the old URL from the Description field
4. insert the current URL in the Website field

![image](https://github.com/UMCUGenetics/hpcguix-web/assets/390889/9341cf20-33e7-48f7-9be8-de3177a8bf5b)

**Comment by roelj** [comment]
Done. Thanks!
