### ISSUE TITLE
Better search heuristics

### ISSUE THREAD

**Issue by rekado** [UMCUGenetics/hpcguix-web#4]
Searching for "macs" finds a lot of packages, most of which are of the form e**macs**-foo.  The actual "macs" package can be found on page 22.

This is because datatables sorts the results table by name by default.

**Comment by rekado** [comment]
One option here is to disable "smart" searching and use "regex" search instead (i.e. with `.search(str, true, false)`).

**Comment by roelj** [comment]
That may provide better search results indeed. We could also add a hidden column and use the scoring system Ludovic introduced in `guix package --search`.

**Comment by rekado** [comment]
The relevance score is only computed during a search, so we cannot get it from packages.json, which is what provides the contents for the big table IIUC.

**Comment by roelj** [comment]
Ah yes.  You are right.

**Comment by rekado** [comment]
Another thing I once added to the old guix-web was to match on the module name, so that "bioinfo" would also show all packages in the bioinformatics module, despite not containing the word "bioinfo" in the description or synopsis.

**Comment by roelj** [comment]
Thanks for the great new features.  Should we add `hpcguix-web.min.js` to the javascript licenses page?

**Comment by roelj** [comment]
I added `hpcguix-web.min.js` to the javascript licenses page in commit 830568a53cb7c6b3a54c23e268693fe7cd26b8c2, but LibreJS still blocks it.  Do we need an inline tag as well?

**Comment by rekado** [comment]
Having it in the table ought to be sufficient.  The inline license comment is lost during minification, unfortunately.  You may need to restart the browser as LibreJS doesn't seem to update the license info otherwise.

**Comment by roelj** [comment]
That's it.  Restarting the browser updated the license info in LibreJS.
So it works now.

Thanks again for your great work on the improved search capabilities.
