### ISSUE TITLE
How to link to a search?

### ISSUE THREAD

**Issue by swedebugia** [UMCUGenetics/hpcguix-web#9]
Earlier http://guix.mdc-berlin.de/packages?/?search=bioinfo worked. 
Now it does not seem to accept GET:
http://guix.mdc-berlin.de/?search=bioinfo -> does not search for bioinfo

**Comment by roelj** [comment]
I don't think it's possible, but it is a nice feature suggestion.

What you could do, but this is probably not what you want, is point to a package:
https://guix.mdc-berlin.de/package/bamtools
